#!/bin/bash
# install Google DNS servers

if ! grep -q '^nameserver 8.8.8.8$' /etc/resolv.conf; then
    echo 'nameserver 8.8.8.8' >> /etc/resolv.conf
fi
if ! grep -q '^nameserver 8.8.4.4$' /etc/resolv.conf; then
    echo 'nameserver 8.8.4.4' >> /etc/resolv.conf
fi