#!/bin/bash

#$ echo "Hello" | tr "e" "E"
#HEllo
#Spaces being transformed to hyphens
#
#$ echo "Hello how are you" | tr " " '-'
#Hello-how-are-you
#Digits (numerals) being deleted
#
#$ echo "Hello how are you 1234" | tr -d [0-9]
#Hello how are you 
#
#In a given fragment of text, delete all the lowercase characters a - z.

tr -d [a-z]

#or
#tr -d '[:lower:]'

#or
#read A
#while [[ -n "$A" ]] 
#do
#  echo "$A" | tr -d [a-z]
#  read A
#done
#echo ""
