#!/bin/bash

# You are given a CSV file where each row contains the name of a city and its state separated by a comma.
# Restructure the file so that three consecutive rows are folded into one line and are separated by semicolons.

paste -d";" - - -
