#!/bin/bash

# You are given a CSV file where each row contains the name of a city and its state separated by a comma.
# Replace the newlines in the input with tabs as demonstrated in the sample.

#paste -s
#paste -s -
paste -d'\t' -s /dev/stdin
